# Form implementation generated from reading ui file '.\bmi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(999, 653)
        Dialog.setStyleSheet("* {\n"
"    font-size:20px;\n"
"}\n"
"QPushButton{\n"
"    height:50px\n"
"}\n"
"QLabel{\n"
"    color:blue\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.height = QtWidgets.QLineEdit(parent=Dialog)
        self.height.setObjectName("height")
        self.horizontalLayout.addWidget(self.height)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.weight = QtWidgets.QLineEdit(parent=Dialog)
        self.weight.setObjectName("weight")
        self.horizontalLayout_2.addWidget(self.weight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setStyleSheet("QPushButton { color: red }\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setStyleSheet("* {\n"
"    backgroud-color:rgb(112, 229, 255)\n"
"}")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.res = QtWidgets.QLabel(parent=Dialog)
        self.res.setWordWrap(True)
        self.res.setObjectName("res")
        self.verticalLayout_2.addWidget(self.res)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BMI计算器"))
        self.label_6.setText(_translate("Dialog", "计算BMI"))
        self.label.setText(_translate("Dialog", "请输入身高:"))
        self.label_2.setText(_translate("Dialog", "请输入体重:"))
        self.pushButton.setText(_translate("Dialog", "计算BMI"))
        self.label_3.setText(_translate("Dialog", "提示：\n"
"1、中国成人居民BMI衡量标准是小于等于18.4为消瘦，18.5-23.9为正常，24-27.9为超重，大于等于28为肥胖。\n"
"2、最理想的BMI数值为22，理想体重 = 22 ×身高2 （米），±10%波动\n"
""))
        self.label_4.setText(_translate("Dialog", "你的计算结果:"))
        self.res.setText(_translate("Dialog", "BMI：27.18，属于超重\n"
"您的理想体重为：68KG\n"
""))
