# Form implementation generated from reading ui file '.\rm_dir.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_rm_dir(object):
    def setupUi(self, rm_dir):
        rm_dir.setObjectName("rm_dir")
        rm_dir.resize(571, 446)
        rm_dir.setStyleSheet("*{\n"
"    font-size:18px;\n"
"}\n"
"QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(0, 170, 255)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(rm_dir)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=rm_dir)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_dir = QtWidgets.QPushButton(parent=rm_dir)
        self.pushButton_dir.setObjectName("pushButton_dir")
        self.horizontalLayout.addWidget(self.pushButton_dir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=rm_dir)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_dir = QtWidgets.QLineEdit(parent=rm_dir)
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.horizontalLayout_2.addWidget(self.lineEdit_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_scan = QtWidgets.QPushButton(parent=rm_dir)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.verticalLayout.addWidget(self.pushButton_scan)
        self.label_3 = QtWidgets.QLabel(parent=rm_dir)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.listWidget = QtWidgets.QListWidget(parent=rm_dir)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton_remove = QtWidgets.QPushButton(parent=rm_dir)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.verticalLayout.addWidget(self.pushButton_remove)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(5, 1)

        self.retranslateUi(rm_dir)
        QtCore.QMetaObject.connectSlotsByName(rm_dir)

    def retranslateUi(self, rm_dir):
        _translate = QtCore.QCoreApplication.translate
        rm_dir.setWindowTitle(_translate("rm_dir", "删除指定文件"))
        self.label.setText(_translate("rm_dir", "请选择要递归描的目录:"))
        self.pushButton_dir.setText(_translate("rm_dir", "请选择目录"))
        self.label_2.setText(_translate("rm_dir", "已选择目录:"))
        self.pushButton_scan.setText(_translate("rm_dir", "递归扫描文件夹"))
        self.label_3.setText(_translate("rm_dir", "扫描结果:"))
        self.pushButton_remove.setText(_translate("rm_dir", "删除选中的文件"))
