# Form implementation generated from reading ui file 'stock_plot.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_stock(object):
    def setupUi(self, stock):
        stock.setObjectName("stock")
        stock.resize(542, 458)
        stock.setStyleSheet("* {\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:rgb(85, 85, 255);\n"
"    backgroud-color:rgb(85, 255, 255)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(stock)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=stock)
        self.label.setStyleSheet("* {\n"
"    font-size:16px;\n"
"}\n"
"QPushButton{\n"
"    color:rgb(0, 255, 255)\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_select = QtWidgets.QComboBox(parent=stock)
        self.comboBox_select.setObjectName("comboBox_select")
        self.comboBox_select.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_select)
        self.pushButton_load = QtWidgets.QPushButton(parent=stock)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_loading = QtWidgets.QPushButton(parent=stock)
        self.pushButton_loading.setObjectName("pushButton_loading")
        self.verticalLayout.addWidget(self.pushButton_loading)
        self.widget_qtgraph = PlotWidget(parent=stock)
        self.widget_qtgraph.setObjectName("widget_qtgraph")
        self.verticalLayout.addWidget(self.widget_qtgraph)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 8)

        self.retranslateUi(stock)
        QtCore.QMetaObject.connectSlotsByName(stock)

    def retranslateUi(self, stock):
        _translate = QtCore.QCoreApplication.translate
        stock.setWindowTitle(_translate("stock", "stock"))
        self.label.setText(_translate("stock", "请选择股票"))
        self.comboBox_select.setItemText(0, _translate("stock", "--未选择--"))
        self.pushButton_load.setText(_translate("stock", "加载股票数据"))
        self.pushButton_loading.setText(_translate("stock", "获取股票数据加载图片"))
from pyqtgraph import PlotWidget
