# Form implementation generated from reading ui file '.\add.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add(object):
    def setupUi(self, add):
        add.setObjectName("add")
        add.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(add)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=add)
        self.label.setStyleSheet("* {\n"
"    font-size:18px;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=add)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.sno = QtWidgets.QLineEdit(parent=add)
        self.sno.setObjectName("sno")
        self.horizontalLayout.addWidget(self.sno)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=add)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.name = QtWidgets.QLineEdit(parent=add)
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=add)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.chinese = QtWidgets.QLineEdit(parent=add)
        self.chinese.setObjectName("chinese")
        self.horizontalLayout_3.addWidget(self.chinese)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=add)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.math = QtWidgets.QLineEdit(parent=add)
        self.math.setObjectName("math")
        self.horizontalLayout_4.addWidget(self.math)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=add)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.English = QtWidgets.QLineEdit(parent=add)
        self.English.setObjectName("English")
        self.horizontalLayout_5.addWidget(self.English)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.submmit = QtWidgets.QPushButton(parent=add)
        self.submmit.setObjectName("submmit")
        self.verticalLayout.addWidget(self.submmit)

        self.retranslateUi(add)
        QtCore.QMetaObject.connectSlotsByName(add)

    def retranslateUi(self, add):
        _translate = QtCore.QCoreApplication.translate
        add.setWindowTitle(_translate("add", "输入新的学生信息"))
        self.label.setText(_translate("add", "请输入新的学生信息"))
        self.label_2.setText(_translate("add", "学号"))
        self.label_3.setText(_translate("add", "姓名"))
        self.label_4.setText(_translate("add", "语文"))
        self.label_5.setText(_translate("add", "数学"))
        self.label_6.setText(_translate("add", "英语"))
        self.submmit.setText(_translate("add", "提交数据"))
