# Form implementation generated from reading ui file '.\manage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_manage(object):
    def setupUi(self, manage):
        manage.setObjectName("manage")
        manage.resize(663, 562)
        manage.setStyleSheet("* {\n"
"    font-size:18px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(manage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=manage)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(parent=manage)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_excel = QtWidgets.QLabel(parent=manage)
        self.label_excel.setObjectName("label_excel")
        self.horizontalLayout.addWidget(self.label_excel)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=manage)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=manage)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_select = QtWidgets.QPushButton(parent=manage)
        self.pushButton_select.setObjectName("pushButton_select")
        self.horizontalLayout_2.addWidget(self.pushButton_select)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=manage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.add_single_data = QtWidgets.QPushButton(parent=manage)
        self.add_single_data.setObjectName("add_single_data")
        self.verticalLayout.addWidget(self.add_single_data)
        self.remove_data = QtWidgets.QPushButton(parent=manage)
        self.remove_data.setObjectName("remove_data")
        self.verticalLayout.addWidget(self.remove_data)
        self.change_data = QtWidgets.QPushButton(parent=manage)
        self.change_data.setObjectName("change_data")
        self.verticalLayout.addWidget(self.change_data)

        self.retranslateUi(manage)
        QtCore.QMetaObject.connectSlotsByName(manage)

    def retranslateUi(self, manage):
        _translate = QtCore.QCoreApplication.translate
        manage.setWindowTitle(_translate("manage", "Excel管理程序"))
        self.label.setText(_translate("manage", "请选择Excel"))
        self.pushButton.setText(_translate("manage", "选择文件"))
        self.label_excel.setText(_translate("manage", "excel文件未选择"))
        self.label_2.setText(_translate("manage", "学号"))
        self.pushButton_select.setText(_translate("manage", "搜索"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("manage", "学号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("manage", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("manage", "语文"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("manage", "数学"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("manage", "英语"))
        self.add_single_data.setText(_translate("manage", "新增学生数据"))
        self.remove_data.setText(_translate("manage", "删除学生数据"))
        self.change_data.setText(_translate("manage", "修改学生数据"))
