# Form implementation generated from reading ui file '.\show.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_static_2(object):
    def setupUi(self, static_2):
        static_2.setObjectName("static_2")
        static_2.resize(558, 355)
        self.verticalLayout = QtWidgets.QVBoxLayout(static_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=static_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(parent=static_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(static_2)
        QtCore.QMetaObject.connectSlotsByName(static_2)

    def retranslateUi(self, static_2):
        _translate = QtCore.QCoreApplication.translate
        static_2.setWindowTitle(_translate("static_2", "展示统计数据"))
        self.label.setText(_translate("static_2", "统计数据"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("static_2", "语文"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("static_2", "数学"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("static_2", "英语"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("static_2", "最高分"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("static_2", "最低分"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("static_2", "平均分"))
