# Form implementation generated from reading ui file 'phone.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ex_phone(object):
    def setupUi(self, ex_phone):
        ex_phone.setObjectName("ex_phone")
        ex_phone.resize(736, 545)
        self.verticalLayout = QtWidgets.QVBoxLayout(ex_phone)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=ex_phone)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(parent=ex_phone)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.extract = QtWidgets.QPushButton(parent=ex_phone)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.extract.setFont(font)
        self.extract.setStyleSheet("QWidget {\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: white;\n"
"}")
        self.extract.setObjectName("extract")
        self.verticalLayout.addWidget(self.extract)
        self.textEdit_2 = QtWidgets.QTextEdit(parent=ex_phone)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.copy = QtWidgets.QPushButton(parent=ex_phone)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.copy.setFont(font)
        self.copy.setStyleSheet("QWidget {\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: white;\n"
"}")
        self.copy.setObjectName("copy")
        self.verticalLayout.addWidget(self.copy)

        self.retranslateUi(ex_phone)
        QtCore.QMetaObject.connectSlotsByName(ex_phone)

    def retranslateUi(self, ex_phone):
        _translate = QtCore.QCoreApplication.translate
        ex_phone.setWindowTitle(_translate("ex_phone", "手机号提取"))
        self.label.setText(_translate("ex_phone", "请粘贴要提取的内容:"))
        self.extract.setText(_translate("ex_phone", "提取手机号"))
        self.copy.setText(_translate("ex_phone", "复制手机列表"))
