# Form implementation generated from reading ui file '.\dir.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dir(object):
    def setupUi(self, dir):
        dir.setObjectName("dir")
        dir.resize(596, 527)
        self.verticalLayout = QtWidgets.QVBoxLayout(dir)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=dir)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.select = QtWidgets.QPushButton(parent=dir)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.select.setFont(font)
        self.select.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: white;\n"
"}")
        self.select.setObjectName("select")
        self.horizontalLayout.addWidget(self.select)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=dir)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=dir)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.start = QtWidgets.QPushButton(parent=dir)
        self.start.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: white;\n"
"}")
        self.start.setObjectName("start")
        self.verticalLayout.addWidget(self.start)
        self.open_dir = QtWidgets.QPushButton(parent=dir)
        self.open_dir.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 170, 255);\n"
"    color: white;\n"
"}")
        self.open_dir.setObjectName("open_dir")
        self.verticalLayout.addWidget(self.open_dir)

        self.retranslateUi(dir)
        QtCore.QMetaObject.connectSlotsByName(dir)

    def retranslateUi(self, dir):
        _translate = QtCore.QCoreApplication.translate
        dir.setWindowTitle(_translate("dir", "文件整理器"))
        self.label.setText(_translate("dir", "请选择要整理的目录:"))
        self.select.setText(_translate("dir", "选择目录"))
        self.label_2.setText(_translate("dir", "已选择目录:"))
        self.start.setText(_translate("dir", "开始整理"))
        self.open_dir.setText(_translate("dir", "打开目录"))
