# Form implementation generated from reading ui file '.\post.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(583, 504)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.request = QtWidgets.QComboBox(parent=Dialog)
        self.request.setObjectName("request")
        self.request.addItem("")
        self.request.addItem("")
        self.horizontalLayout.addWidget(self.request)
        self.url = QtWidgets.QLineEdit(parent=Dialog)
        self.url.setObjectName("url")
        self.horizontalLayout.addWidget(self.url)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.headers = QtWidgets.QLabel(parent=Dialog)
        self.headers.setObjectName("headers")
        self.verticalLayout.addWidget(self.headers)
        self.textEdit_headers = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_headers.setObjectName("textEdit_headers")
        self.verticalLayout.addWidget(self.textEdit_headers)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.params = QtWidgets.QLabel(parent=Dialog)
        self.params.setObjectName("params")
        self.verticalLayout_2.addWidget(self.params)
        self.textEdit_params = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_params.setObjectName("textEdit_params")
        self.verticalLayout_2.addWidget(self.textEdit_params)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.data = QtWidgets.QLabel(parent=Dialog)
        self.data.setObjectName("data")
        self.verticalLayout_3.addWidget(self.data)
        self.textEdit_data = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_data.setObjectName("textEdit_data")
        self.verticalLayout_3.addWidget(self.textEdit_data)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.summit = QtWidgets.QPushButton(parent=Dialog)
        self.summit.setObjectName("summit")
        self.verticalLayout_4.addWidget(self.summit)
        self.res = QtWidgets.QTextEdit(parent=Dialog)
        self.res.setObjectName("res")
        self.verticalLayout_4.addWidget(self.res)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.request.setItemText(0, _translate("Dialog", "get"))
        self.request.setItemText(1, _translate("Dialog", "post"))
        self.headers.setText(_translate("Dialog", "headers"))
        self.params.setText(_translate("Dialog", "params"))
        self.data.setText(_translate("Dialog", "data"))
        self.summit.setText(_translate("Dialog", "提交请求"))
