# Form implementation generated from reading ui file '.\e_to_w.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_e_to_w(object):
    def setupUi(self, e_to_w):
        e_to_w.setObjectName("e_to_w")
        e_to_w.resize(765, 589)
        e_to_w.setStyleSheet("* {\n"
"    font-size:18px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(e_to_w)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=e_to_w)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=e_to_w)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=e_to_w)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=e_to_w)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(parent=e_to_w)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=e_to_w)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=e_to_w)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(parent=e_to_w)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=e_to_w)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(parent=e_to_w)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=e_to_w)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)

        self.retranslateUi(e_to_w)
        QtCore.QMetaObject.connectSlotsByName(e_to_w)

    def retranslateUi(self, e_to_w):
        _translate = QtCore.QCoreApplication.translate
        e_to_w.setWindowTitle(_translate("e_to_w", "Excel生成word文件"))
        self.label.setText(_translate("e_to_w", "功能:读取excel文件批量生成word文件"))
        self.label_2.setText(_translate("e_to_w", "输入excel文件:"))
        self.pushButton.setText(_translate("e_to_w", "选择excel文件"))
        self.label_3.setText(_translate("e_to_w", "输入word模板:"))
        self.pushButton_2.setText(_translate("e_to_w", "选择word文件"))
        self.label_4.setText(_translate("e_to_w", "输出的目录："))
        self.pushButton_3.setText(_translate("e_to_w", "选择目录"))
        self.pushButton_4.setText(_translate("e_to_w", "批量生成"))
