# Form implementation generated from reading ui file '.\concat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(935, 654)
        Dialog.setStyleSheet("* {\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(0, 170, 255)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.choose_dir = QtWidgets.QPushButton(parent=Dialog)
        self.choose_dir.setObjectName("choose_dir")
        self.horizontalLayout.addWidget(self.choose_dir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.rm_file = QtWidgets.QPushButton(parent=Dialog)
        self.rm_file.setObjectName("rm_file")
        self.horizontalLayout_2.addWidget(self.rm_file)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.save = QtWidgets.QPushButton(parent=Dialog)
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请选择要合并的目录:"))
        self.choose_dir.setText(_translate("Dialog", "选择目录"))
        self.label_2.setText(_translate("Dialog", "扫描excel表如下:"))
        self.rm_file.setText(_translate("Dialog", "移除文件"))
        self.save.setText(_translate("Dialog", "执行合并保存文件"))
